name: Create Branch Protection Rule

on:
  workflow_dispatch: 

jobs:
  create_branch_protection_rule:    
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/github-script@v6
        with:
          cmd: create-branch-protection-rule
          repository: ${{ github.repository }}
          pattern: main
          enforce_admins: true
          required_pull_request_reviews:
          required_approving_review_count: 1
          require_code_owner_reviews: true
          required_status_checks:
          strict: true