name: Create Branch Protection Rule

on:
  workflow_dispatch: 

jobs:
  create_branch_protection_rule:    
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create branch protection rule
        run: |           
            # Define variables
            REPO_OWNER="${{github.repository_owner}}"
            REPO_NAME="${{github.repository}}"
            BRANCH_PATTERN="main" # Customize your branch pattern
            REVIEW_REQUIRED=true
            CODE_OWNERS=true
            STATUS_CHECKS=true
            BYPASS_SETTINGS=false
            echo "$REPO_OWNER"
            echo "$REPO_NAME"
            echo "$BRANCH_PATTERN"

            # Create branch protection rule
            curl --location --request PUT 'https://api.github.com/repos/"$REPO_NAME"/branches/"$BRANCH_PATTERN"/protection' \
                --header 'Content-Type: application/json' \
                --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                --data '{
                  "required_status_checks": {
                    "strict": true,
                    "contexts": []
                  },
                  "enforce_admins": false,
                  "required_pull_request_reviews": {
                    "dismiss_stale_reviews": true,
                    "require_code_owner_reviews": true,
                    "required_approving_review_count": 1
                  },
                  "restrictions": null
                }'

            echo "Branch protection rule created successfully."        