# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-protection-rule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const protectionRule = {
              pattern: 'main', // Adjust the branch name pattern as needed
              enforce_admins: true, // Apply protection rules to admins
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                require_code_owner_reviews: true,
              }
              required_status_checks: {
                strict: true
              },
            };

            github.repos.createOrUpdateBranchProtectionRule({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branchProtectionRule: protectionRule,
            });
