name: Create Branch Protection Rule

on:
  workflow_dispatch: 
permissions: 
  write-all

jobs:
  create_branch_protection_rule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create branch protection rule
        run: |           
            # Define variables
            REPO_OWNER="${{github.repository_owner}}"
            REPO_NAME="${{github.repository}}"
            BRANCH_PATTERN="main" # Customize your branch pattern
            REVIEW_REQUIRED=true
            CODE_OWNERS=true
            STATUS_CHECKS=true
            BYPASS_SETTINGS=false

            # Create branch protection rule
            curl -X PUT \
              -H "Accept: application/vnd.github.luke-cage-preview+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d '{
                    "required_status_checks": {
                      "strict": true,
                      "contexts": []
                    },
                    "enforce_admins": false,
                    "required_pull_request_reviews": {
                      "dismiss_stale_reviews": true,
                      "require_code_owner_reviews": '$CODE_OWNERS',
                      "required_approving_review_count": 1
                    },
                    "restrictions": {
                      "users": [],
                      "teams": [],
                      "apps": []
                    }
                  }' \
              "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/branches/$BRANCH_PATTERN/protection"

            echo "Branch protection rule created successfully."

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}