name: Create Branch Protection Rule

on:
  workflow_dispatch: 

jobs:
  create_branch_protection_rule:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create branch protection rule
        run: |           
            # Define variables
            REPO_OWNER="${{github.repository_owner}}"
            REPO_NAME="${{github.repository}}"
            BRANCH_PATTERN="main" # Customize your branch pattern
            REVIEW_REQUIRED=true
            CODE_OWNERS=true
            STATUS_CHECKS=true
            BYPASS_SETTINGS=false
            echo "$REPO_OWNER"
            echo "$REPO_NAME"
            echo "$BRANCH_PATTERN"

            # Create branch protection rule
            curl -X PUT \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer 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" \
              -d '{
                    "required_status_checks": {
                      "strict": true,
                      "contexts": []
                    },
                    "enforce_admins": false,
                    "required_pull_request_reviews": {
                      "dismiss_stale_reviews": true,
                      "require_code_owner_reviews": '$CODE_OWNERS',
                      "required_approving_review_count": 1
                    },
                    "restrictions": null
                  }' \
              "https://api.github.com/repos/$REPO_NAME/branches/$BRANCH_PATTERN/protection"

            echo "Branch protection rule created successfully."

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}