name: Create Branch Protection Rule

on:
  workflow_dispatch: 

jobs:
  create_branch_protection_rule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Branch Protection Rule
        uses: actions/github-script@v6
        with:
          script: |
            const branchNamePattern = "main";
            const requirePullRequestReviews = true;
            const requireCodeOwnerReviews = true;
            const requireStatusChecks = true;
            const requireSignedCommits = false;
            const enforceAdmins = false;
            const dismissStaleReviews = false;
            const requireLinearHistory = false;
            const allowForcePushes = false;
            const allowDeletions = false;

            const octokit = new github.GitHub(process.env.GITHUB_TOKEN);
            const context = github.context;

            const owner = context.repo.owner;
            const repo = context.repo.repo;

            await octokit.repos.createBranchProtection({
              owner,
              repo,
              branch: branchNamePattern,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: dismissStaleReviews,
              },
              required_status_checks: {
                contexts: [],
                strict: true,
              },
              enforce_admins: enforceAdmins,
              required_linear_history: requireLinearHistory,
              allow_force_pushes: allowForcePushes,
              allow_deletions: allowDeletions,
              restrictions: null,
              required_code_owner_reviews: {
                include_admins: true,
              },
              required_signatures: requireSignedCommits,
            });
