name: Create Branch Protection Rule

on:
  workflow_dispatch: 
permissions: 
  write-all

jobs:
  create-protection-rule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const protectionRule = {
              pattern: 'main', // Adjust the branch name pattern as needed
              enforce_admins: true, // Apply protection rules to admins
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                require_code_owner_reviews: true,
              },
              restrictions: {
                users: [], // Restrict direct pushes to matching branches
                teams: [],
                apps: [],
              },
              required_status_checks: {
                strict: true,
                contexts: [                 
                ],
              },
            };
            github.repos.createOrUpdateBranchProtectionRule({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branchProtectionRule: protectionRule,
            });